import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";
import AuthLayout from "~/app/_components/layouts/authLayout";
import { Toaster } from "~/components/ui/sonner";
import { SessionProvider } from "next-auth/react";
import Navbar from "~/app/_components/navbar/navbar";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <SessionProvider>
          <TRPCReactProvider>
            <Toaster richColors position="top-center"/>
            <AuthLayout>
              <Navbar />
              {children}
            </AuthLayout>
          </TRPCReactProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
