export interface Round1 {
  question: string;
  code: { code: string; language: string } | null;
  hint: string;
  level: number;
  roundId: number;
  maxPoints: number;
  options: {
    option: string;
    isCorrect: boolean;
    code: boolean | null;
    questionId: number;
  }[];
}

export const Round1Details: Round1[] = [
  {
    question: "If CAT is coded as 3120, how is DOG coded?",
    code: null,
    hint: "Assign numbers (A=1, B=2, …, Z=26) and subtract each from 27.",
    level: 12,
    roundId: 1,
    maxPoints: 10,
    options: [
      {
        option: "4715",
        isCorrect: false,
        code: null,
        questionId: 1,
      },
      {
        option: "4157",
        isCorrect: true,
        code: null,
        questionId: 1,
      },
      {
        option: "7145",
        isCorrect: false,
        code: null,
        questionId: 1,
      },
      {
        option: "7415",
        isCorrect: false,
        code: null,
        questionId: 1,
      },
    ],
  },
  {
    question: "If APPLE is coded as 25516125, how is ORANGE coded?",
    code: null,
    hint: "Assign numbers to letters (A=1, B=2, ..., Z=26) and reverse the order.",
    level: 14,
    roundId: 1,
    maxPoints: 10,
    options: [
      {
        option: "181914715",
        isCorrect: false,
        code: null,
        questionId: 1,
      },
      {
        option: "151814915 ",
        isCorrect: true,
        code: null,
        questionId: 1,
      },
      {
        option: "181914515",
        isCorrect: false,
        code: null,
        questionId: 1,
      },
      {
        option: "151915915",
        isCorrect: false,
        code: null,
        questionId: 1,
      },
    ],
  },
  {
    question: "What comes next? 1, 11, 21, 1211, 111221, ?",
    code: null,
    hint: "Each term describes the previous one (Look-and-Say sequence).",
    level: 7,
    roundId: 1,
    maxPoints: 5,
    options: [
      {
        option: "312211",
        isCorrect: true,
        code: null,
        questionId: 2,
      },
      {
        option: "222111",
        isCorrect: false,
        code: null,
        questionId: 2,
      },
      {
        option: "112233",
        isCorrect: false,
        code: null,
        questionId: 2,
      },
      {
        option: "13112221",
        isCorrect: false,
        code: null,
        questionId: 2,
      },
    ],
  },
  {
    question: "What comes next in the pattern? A, C, F, J, O, ?",
    code: null,
    hint: "Find the difference between positions in the alphabet.",
    level: 19,
    roundId: 1,
    maxPoints: 5,
    options: [
      {
        option: "U",
        isCorrect: true,
        code: null,
        questionId: 2,
      },
      {
        option: "S",
        isCorrect: false,
        code: null,
        questionId: 2,
      },
      {
        option: "R",
        isCorrect: false,
        code: null,
        questionId: 2,
      },
      {
        option: "T",
        isCorrect: false,
        code: null,
        questionId: 2,
      },
    ],
  },
  {
    question: "If A=52 and Z=2, then what is the sum of SHADOW?",
    code: null,
    hint: "Assign numbers to letters (A=26, B=25, ..., Z=1), Add and double it.",
    level: 25,
    roundId: 1,
    maxPoints: 15,
    options: [
      {
        option: "184",
        isCorrect: true,
        code: null,
        questionId: 3,
      },
      {
        option: "178",
        isCorrect: false,
        code: null,
        questionId: 3,
      },
      {
        option: "190",
        isCorrect: false,
        code: null,
        questionId: 3,
      },
      {
        option: "168",
        isCorrect: false,
        code: null,
        questionId: 3,
      },
    ],
  },
  {
    question: "I am tall when I'm young, and short when I'm old. What am I?",
    code: null,
    hint: "Think of something that burns.",
    level: 14,
    roundId: 1,
    maxPoints: 10,
    options: [
      {
        option: "Candle",
        isCorrect: true,
        code: null,
        questionId: 4,
      },
      {
        option: "Clock",
        isCorrect: false,
        code: null,
        questionId: 4,
      },
      {
        option: "Shadow",
        isCorrect: false,
        code: null,
        questionId: 4,
      },
      {
        option: "Tree",
        isCorrect: false,
        code: null,
        questionId: 4,
      },
    ],
  },
  {
    question:
      "What comes once in a minute, twice in a moment, but never in a thousand years?",
    code: null,
    hint: "Look at the letters!",
    level: 4,
    roundId: 1,
    maxPoints: 5,
    options: [
      {
        option: "Time",
        isCorrect: false,
        code: null,
        questionId: 5,
      },
      {
        option: "Second",
        isCorrect: false,
        code: null,
        questionId: 5,
      },
      {
        option: "The sun",
        isCorrect: false,
        code: null,
        questionId: 5,
      },
      {
        option: "The M",
        isCorrect: true,
        code: null,
        questionId: 5,
      },
    ],
  },
  {
    question: "What does this Python code print?",
    code: {
      code: `x = "5"
y = "5"
print(x + y)`,
      language: "python",
    },
    hint: "String concatenation, not addition.",
    level: 16,
    maxPoints: 10,
    roundId: 1,
    options: [
      {
        option: "10",
        code: null,
        isCorrect: false,
        questionId: 6,
      },
      {
        option: "55",
        code: null,
        isCorrect: true,
        questionId: 6,
      },
      {
        option: "Error",
        code: null,
        isCorrect: false,
        questionId: 6,
      },
      {
        option: "None",
        code: null,
        isCorrect: false,
        questionId: 6,
      },
    ],
  },
  {
    question: "Decode the following: 01001000 01001001",
    code: {
      code: `binary_text = "01001000 01001001"
print(''.join([chr(int(b, 2)) for b in binary_text.split()]))`,
      language: "python",
    },
    hint: "Convert binary to ASCII.",
    level: 28,
    roundId: 1,
    maxPoints: 10,
    options: [
      {
        option: "BYE",
        isCorrect: false,
        code: null,
        questionId: 1,
      },
      {
        option: "Hi",
        isCorrect: true,
        code: null,
        questionId: 1,
      },
      {
        option: "OK",
        isCorrect: false,
        code: null,
        questionId: 1,
      },
      {
        option: "ON",
        isCorrect: false,
        code: null,
        questionId: 1,
      },
    ],
  },
  {
    question:
      "You have a 3-gallon jug and a 5-gallon jug. How do you measure out exactly 4 gallons?",
    code: null,
    hint: "Think about transferring water between the two jugs strategically to isolate exactly 4 gallons in one of them. Use the difference in their capacities to your advantage!",
    level: 24,
    roundId: 1,
    maxPoints: 15,
    options: [
      {
        option:
          "Fill the 5-gallon jug and pour into the 3-gallon jug until it is full. You have 2 gallons left in the 5-gallon jug. Empty the 3-gallon jug and pour the 2 gallons into it. Fill the 5-gallon jug again and pour into the 3-gallon jug until it is full. You now have exactly 4 gallons in the 5-gallon jug.",
        isCorrect: true,
        code: null,
        questionId: 6,
      },
      {
        option: "Fill the 3-gallon jug twice and pour into the 5-gallon jug.",
        isCorrect: false,
        code: null,
        questionId: 6,
      },
      {
        option:
          "Fill the 5-gallon jug and pour into the 3-gallon jug until it is full. You have 2 gallons left in the 5-gallon jug.",
        isCorrect: false,
        code: null,
        questionId: 6,
      },
    ],
  },
  {
    question: "What will be the output of the following C code?",
    code: {
      code: `#include <stdio.h>
int main() {
    int x = 5;
    printf("%d", x++ * ++x);
    return 0;
}
`,
      language: "c",
    },
    hint: "Beware of sequence points in C.",
    level: 8,
    roundId: 1,
    maxPoints: 10,
    options: [
      {
        option: "Undefined behavior",
        isCorrect: true,
        code: null,
        questionId: 7,
      },
      {
        option: "30",
        isCorrect: false,
        code: null,
        questionId: 7,
      },
      {
        option: "25",
        isCorrect: false,
        code: null,
        questionId: 7,
      },
      {
        option: "36",
        isCorrect: false,
        code: null,
        questionId: 7,
      },
    ],
  },
  {
    question: "What does this JavaScript snippet output?",
    code: {
      code: `console.log(0.1 + 0.2 === 0.3);`,
      language: "js",
    },
    hint: "Floating-point precision issue.",
    level: 16,
    roundId: 1,
    maxPoints: 5,
    options: [
      {
        option: "true",
        isCorrect: false,
        code: null,
        questionId: 8,
      },
      {
        option: "false",
        isCorrect: false,
        code: null,
        questionId: 8,
      },
      {
        option: "undefined",
        isCorrect: false,
        code: null,
        questionId: 8,
      },
      {
        option: "Nan",
        isCorrect: false,
        code: null,
        questionId: 8,
      },
    ],
  },
  {
    question: "Which of these is NOT an encryption algorithm?",
    code: null,
    hint: "One is a hashing algorithm, not encryption.",
    level: 21,
    roundId: 1,
    maxPoints: 15,
    options: [
      {
        option: "AES",
        isCorrect: false,
        code: null,
        questionId: 9,
      },
      {
        option: "RSA",
        isCorrect: false,
        code: null,
        questionId: 9,
      },
      {
        option: "SHA-256",
        isCorrect: true,
        code: null,
        questionId: 9,
      },
      {
        option: "DES",
        isCorrect: false,
        code: null,
        questionId: 9,
      },
    ],
  },
  {
    question: "The more you take, the more you leave behind. What am I?",
    code: null,
    hint: "Think about movement.",
    level: 9,
    roundId: 1,
    maxPoints: 15,
    options: [
      {
        option: "Footsteps",
        isCorrect: true,
        code: null,
        questionId: 9,
      },
      {
        option: "Time",
        isCorrect: false,
        code: null,
        questionId: 9,
      },
      {
        option: "Thoughts",
        isCorrect: false,
        code: null,
        questionId: 9,
      },
      {
        option: "Shadows",
        isCorrect: false,
        code: null,
        questionId: 9,
      },
    ],
  },
  {
    question: "Which of these is a brute-force attack method?",
    code: null,
    hint: "Guessing passwords systematically.",
    level: 18,
    roundId: 1,
    maxPoints: 10,
    options: [
      {
        option: "Dictionary attack",
        isCorrect: true,
        code: null,
        questionId: 10,
      },
      {
        option: "Phishing",
        isCorrect: false,
        code: null,
        questionId: 10,
      },
      {
        option: "DoS",
        isCorrect: false,
        code: null,
        questionId: 10,
      },
      {
        option: "Man-in-the-middle",
        isCorrect: false,
        code: null,
        questionId: 10,
      },
    ],
  },
  {
    question: "A farmer has 17 sheep, all but 9 run away. How many are left?",
    code: null,
    hint: "Focus on 'all but 9'.",
    level: 5,
    roundId: 1,
    maxPoints: 5,
    options: [
      {
        option: "17",
        isCorrect: false,
        code: null,
        questionId: 11,
      },
      {
        option: "8",
        isCorrect: false,
        code: null,
        questionId: 11,
      },
      {
        option: "9",
        isCorrect: true,
        code: null,
        questionId: 11,
      },
      {
        option: "0",
        isCorrect: false,
        code: null,
        questionId: 11,
      },
    ],
  },
  {
    question: "Which number comes next in the series? 8, 27, 64, 125, ?",
    code: null,
    hint: "Cube the numbers (2³, 3³, 4³…).",
    level: 23,
    roundId: 1,
    maxPoints: 15,
    options: [
      {
        option: "216",
        isCorrect: true,
        code: null,
        questionId: 12,
      },
      {
        option: "144",
        isCorrect: false,
        code: null,
        questionId: 12,
      },
      {
        option: "225",
        isCorrect: false,
        code: null,
        questionId: 12,
      },
      {
        option: "256",
        isCorrect: false,
        code: null,
        questionId: 12,
      },
    ],
  },
  {
    question: "What does an AI model learn from?",
    code: null,
    hint: "It improves based on past information.",
    level: 11,
    roundId: 1,
    maxPoints: 5,
    options: [
      {
        option: "Training Data",
        isCorrect: true,
        code: null,
        questionId: 13,
      },
      {
        option: "Random Numbers",
        isCorrect: false,
        code: null,
        questionId: 13,
      },
      {
        option: "A CPU",
        isCorrect: false,
        code: null,
        questionId: 13,
      },
      {
        option: "A compiler",
        isCorrect: false,
        code: null,
        questionId: 13,
      },
    ],
  },
  {
    question: "Which is an example of supervised learning?",
    code: null,
    hint: "Requires labeled data.",
    level: 26,
    roundId: 1,
    maxPoints: 15,
    options: [
      {
        option: "Image classification",
        isCorrect: true,
        code: null,
        questionId: 14,
      },
      {
        option: "Clustering",
        isCorrect: false,
        code: null,
        questionId: 14,
      },
      {
        option: "Reinforcement learning",
        isCorrect: false,
        code: null,
        questionId: 14,
      },
      {
        option: "Sorting algorithms",
        isCorrect: false,
        code: null,
        questionId: 14,
      },
    ],
  },
  {
    question: "Which material is a good electrical conductor?",
    code: null,
    hint: "Not cheap enough to use in wirings",
    level: 13,
    roundId: 1,
    maxPoints: 10,
    options: [
      {
        option: "Copper",
        isCorrect: false,
        code: null,
        questionId: 15,
      },
      {
        option: "Silver",
        isCorrect: true,
        code: null,
        questionId: 15,
      },
      {
        option: "Iron",
        isCorrect: false,
        code: null,
        questionId: 15,
      },
      {
        option: "Gold",
        isCorrect: false,
        code: null,
        questionId: 15,
      },
    ],
  },
  {
    question:
      "What do you throw away when you need it and take back when you don't?",
    code: null,
    hint: "Used in the sea.",
    level: 20,
    roundId: 1,
    maxPoints: 5,
    options: [
      {
        option: "Anchor",
        isCorrect: true,
        code: null,
        questionId: 16,
      },
      {
        option: "Parachute",
        isCorrect: false,
        code: null,
        questionId: 16,
      },
      {
        option: "Key",
        isCorrect: false,
        code: null,
        questionId: 16,
      },
      {
        option: "Map",
        isCorrect: false,
        code: null,
        questionId: 16,
      },
    ],
  },
  {
    question:
      " I'm not alive, but I grow. I don't have lungs, but I need air. What am I?",
    code: null,
    hint: "It burns.",
    level: 25,
    roundId: 1,
    maxPoints: 15,
    options: [
      {
        option: "Fire",
        isCorrect: true,
        code: null,
        questionId: 17,
      },
      {
        option: "Tree",
        isCorrect: false,
        code: null,
        questionId: 17,
      },
      {
        option: "Fish",
        isCorrect: false,
        code: null,
        questionId: 17,
      },
      {
        option: "Cloud",
        isCorrect: false,
        code: null,
        questionId: 17,
      },
    ],
  },
  {
    question:
      "A snail climbs 5m in the day and slips 4m at night. How many days will it take to reach the top of a 20m wall?",
    code: null,
    hint: "The last 5 meters don't require a slip!",
    level: 29,
    roundId: 1,
    maxPoints: 15,
    options: [
      {
        option: "15",
        isCorrect: true,
        code: null,
        questionId: 17,
      },
      {
        option: "20",
        isCorrect: false,
        code: null,
        questionId: 17,
      },
      {
        option: "16",
        isCorrect: false,
        code: null,
        questionId: 17,
      },
      {
        option: "19",
        isCorrect: false,
        code: null,
        questionId: 17,
      },
    ],
  },
  {
    question:
      "Two mothers and two daughters go to a bakery and buy one muffin each. They only buy three muffins in total. How?",
    code: null,
    hint: "Think about generational relationships!",
    level: 8,
    roundId: 1,
    maxPoints: 15,
    options: [
      {
        option: "One is a grandmother, mother, and daughter",
        isCorrect: true,
        code: null,
        questionId: 17,
      },
      {
        option: "They shared a muffin",
        isCorrect: false,
        code: null,
        questionId: 17,
      },
      {
        option: "The shop ran out",
        isCorrect: false,
        code: null,
        questionId: 17,
      },
      {
        option: "One got a refund",
        isCorrect: false,
        code: null,
        questionId: 17,
      },
    ],
  },
  {
    question: "Find the missing number in this sequence: 2, 6, 12, 20, ?",
    code: null,
    hint: "Look at the pattern of adding consecutive even numbers.",
    level: 17,
    roundId: 1,
    maxPoints: 15,
    options: [
      {
        option: "30",
        isCorrect: true,
        code: null,
        questionId: 17,
      },
      {
        option: "28",
        isCorrect: false,
        code: null,
        questionId: 17,
      },
      {
        option: "32",
        isCorrect: false,
        code: null,
        questionId: 17,
      },
      {
        option: "26",
        isCorrect: false,
        code: null,
        questionId: 17,
      },
    ],
  },
  {
    question:
      "If 'HELLO' is encrypted using the Caesar cipher with a shift of 3, what is the result?",
    code: null,
    hint: "Shift each letter forward in the alphabet.",
    level: 28,
    roundId: 1,
    maxPoints: 15,
    options: [
      {
        option: "KHOOR",
        isCorrect: true,
        code: null,
        questionId: 17,
      },
      {
        option: "LIPPS",
        isCorrect: false,
        code: null,
        questionId: 17,
      },
      {
        option: "GDKKN",
        isCorrect: false,
        code: null,
        questionId: 17,
      },
      {
        option: "HELLO",
        isCorrect: false,
        code: null,
        questionId: 17,
      },
    ],
  },
  {
    question: "Decode this cipher: 'DRO YFOB KVV' (Caesar shift by 10).",
    code: null,
    hint: "A creation of Dr. Julius Caesar.",
    level: 22,
    roundId: 1,
    maxPoints: 15,
    options: [
      {
        option: "The Lion King",
        isCorrect: true,
        code: null,
        questionId: 17,
      },
      {
        option: "The Dark Knight",
        isCorrect: false,
        code: null,
        questionId: 17,
      },
      {
        option: "The Code Breaker",
        isCorrect: false,
        code: null,
        questionId: 17,
      },
      {
        option: "The Matrix",
        isCorrect: false,
        code: null,
        questionId: 17,
      },
    ],
  },
  {
    question: `If "SUN" = "VPQ", "MOON" = "QQPP", then "STAR" = ?`,
    code: null,
    hint: "Each letter is shifted by 2.",
    level: 15,
    roundId: 1,
    maxPoints: 15,
    options: [
      {
        option: "UVDT",
        isCorrect: true,
        code: null,
        questionId: 17,
      },
      {
        option: "TVDU",
        isCorrect: false,
        code: null,
        questionId: 17,
      },
      {
        option: "QWRT",
        isCorrect: false,
        code: null,
        questionId: 17,
      },
      {
        option: "SDFT",
        isCorrect: false,
        code: null,
        questionId: 17,
      },
    ],
  },
  {
    question: `If each letter of the alphabet is assigned an increasing prime number, what is the sum of "ACE"`,
    code: null,
    hint: "Assign numbers to letters (A=2, B=3, C=5, ...) and Add. Super easy.",
    level: 6,
    roundId: 1,
    maxPoints: 15,
    options: [
      {
        option: "13",
        isCorrect: true,
        code: null,
        questionId: 17,
      },
      {
        option: "15",
        isCorrect: false,
        code: null,
        questionId: 17,
      },
      {
        option: "20",
        isCorrect: false,
        code: null,
        questionId: 17,
      },
      {
        option: "23",
        isCorrect: false,
        code: null,
        questionId: 17,
      },
    ],
  },
  {
    question: `If "HELLO" is coded as "IFMMP," how is "WORLD" coded?`,
    code: null,
    hint: "Shift each letter forward in the alphabet.",
    level: 20,
    roundId: 1,
    maxPoints: 15,
    options: [
      {
        option: "XPSME",
        isCorrect: true,
        code: null,
        questionId: 17,
      },
      {
        option: "VPTLD",
        isCorrect: false,
        code: null,
        questionId: 17,
      },
      {
        option: "XPTME",
        isCorrect: false,
        code: null,
        questionId: 17,
      },
      {
        option: "XPQME",
        isCorrect: false,
        code: null,
        questionId: 17,
      },
    ],
  },
  {
    question: `I have keys but open no locks. I have space but no room. You can enter but can't leave. What am I?`,
    code: null,
    hint: "Its right infront of you. LOL",
    level: 10,
    roundId: 1,
    maxPoints: 15,
    options: [
      {
        option: "Keyboard",
        isCorrect: true,
        code: null,
        questionId: 17,
      },
      {
        option: "Map",
        isCorrect: false,
        code: null,
        questionId: 17,
      },
      {
        option: "Puzzle",
        isCorrect: false,
        code: null,
        questionId: 17,
      },
      {
        option: "Book",
        isCorrect: false,
        code: null,
        questionId: 17,
      },
    ],
  },
  {
    question: `Which technology is expected to revolutionize chip manufacturing by replacing silicon with more efficient materials?`,
    code: null,
    hint: "It consists of a soft metal.",
    level: 29,
    roundId: 1,
    maxPoints: 15,
    options: [
      {
        option: "Gallium Nitride",
        isCorrect: true,
        code: null,
        questionId: 17,
      },
      {
        option: "Quantum Dots",
        isCorrect: false,
        code: null,
        questionId: 17,
      },
      {
        option: "Carbon Nanotubes",
        isCorrect: false,
        code: null,
        questionId: 17,
      },
      {
        option: "Perovskite Semiconductors",
        isCorrect: false,
        code: null,
        questionId: 17,
      },
    ],
  },
  {
    question: `What is the primary focus of the European Union's AI Act, passed in 2024?`,
    code: null,
    hint: "Consider the balance between innovation and ethical concerns.",
    level: 3,
    roundId: 1,
    maxPoints: 15,
    options: [
      {
        option: "Banning all AI systems in Europe",
        isCorrect: false,
        code: null,
        questionId: 17,
      },
      {
        option: "Regulating AI based on risk levels",
        isCorrect: true,
        code: null,
        questionId: 17,
      },
      {
        option: "Promoting AI in military applications",
        isCorrect: false,
        code: null,
        questionId: 17,
      },
      {
        option: "Restricting AI development to government agencies",
        isCorrect: false,
        code: null,
        questionId: 17,
      },
    ],
  },
  {
    question: `Which recent innovation in battery technology has shown promise for significantly increasing energy density?`,
    code: null,
    hint: "It uses a solid electrolyte instead of a liquid one.",
    level: 2,
    roundId: 1,
    maxPoints: 15,
    options: [
      {
        option: "Graphene Supercapacitors",
        isCorrect: false,
        code: null,
        questionId: 17,
      },
      {
        option: "Solid-State Batteries",
        isCorrect: true,
        code: null,
        questionId: 17,
      },
      {
        option: "Lithium-Sulfur Batteries",
        isCorrect: false,
        code: null,
        questionId: 17,
      },
      {
        option: "Sodium-Ion Batteries",
        isCorrect: false,
        code: null,
        questionId: 17,
      },
    ],
  },
  {
    question: `Which of the following rivers crosses the most international borders?`,
    code: null,
    hint: "It flows through 10 countries and starts with a D.",
    level: 1,
    roundId: 1,
    maxPoints: 15,
    options: [
      {
        option: "Danube",
        isCorrect: true,
        code: null,
        questionId: 17,
      },
      {
        option: "Amazon",
        isCorrect: false,
        code: null,
        questionId: 17,
      },
      {
        option: "Nile",
        isCorrect: false,
        code: null,
        questionId: 17,
      },
      {
        option: "Mekong",
        isCorrect: false,
        code: null,
        questionId: 17,
      },
    ],
  },
  {
    question: `Which desert is known for being the driest place on Earth?`,
    code: null,
    hint: "Its precipitation is less than 1mm per year and located in South America .",
    level: 4,
    roundId: 1,
    maxPoints: 15,
    options: [
      {
        option: "Kalahari Desert",
        isCorrect: false,
        code: null,
        questionId: 17,
      },
      {
        option: "Atacama Desert",
        isCorrect: true,
        code: null,
        questionId: 17,
      },
      {
        option: "Gobi Desert",
        isCorrect: false,
        code: null,
        questionId: 17,
      },
      {
        option: "Namib Desert",
        isCorrect: false,
        code: null,
        questionId: 17,
      },
    ],
  },
  {
    question: `Which of these historical civilizations developed one of the earliest known written languages?`,
    code: null,
    hint: "This civilization was located in ancient Mesopotamia.",
    level: 18,
    roundId: 1,
    maxPoints: 15,
    options: [
      {
        option: "Olmec",
        isCorrect: false,
        code: null,
        questionId: 17,
      },
      {
        option: "Harappan",
        isCorrect: false,
        code: null,
        questionId: 17,
      },
      {
        option: "Hittite",
        isCorrect: false,
        code: null,
        questionId: 17,
      },
      {
        option: "Sumerian",
        isCorrect: true,
        code: null,
        questionId: 17,
      },
    ],
  },
  {
    question: `Which celestial body in our solar system is known to have a thick atmosphere and lakes of liquid hydrocarbons?`,
    code: null,
    hint: "A name of a given to a giant in Greek mythology.",
    level: 22,
    roundId: 1,
    maxPoints: 15,
    options: [
      {
        option: "Europa",
        isCorrect: false,
        code: null,
        questionId: 17,
      },
      {
        option: "Titan",
        isCorrect: true,
        code: null,
        questionId: 17,
      },
      {
        option: "Ganymede",
        isCorrect: false,
        code: null,
        questionId: 17,
      },
      {
        option: "Io",
        isCorrect: false,
        code: null,
        questionId: 17,
      },
    ],
  },
  {
    question: `Which mathematician is credited with developing the concept of a "Turing machine"?`,
    code: null,
    hint: "He is considered the father of theoretical computer science. The machine itself has his name.",
    level: 27,
    roundId: 1,
    maxPoints: 15,
    options: [
      {
        option: "John von Neumann",
        isCorrect: false,
        code: null,
        questionId: 17,
      },
      {
        option: "Alan Turing",
        isCorrect: true,
        code: null,
        questionId: 17,
      },
      {
        option: "Kurt Gödel",
        isCorrect: false,
        code: null,
        questionId: 17,
      },
      {
        option: "Claude Shannon",
        isCorrect: false,
        code: null,
        questionId: 17,
      },
    ],
  },
  {
    question: `Which of these elements was first artificially synthesized and does not occur naturally on Earth?`,
    code: null,
    hint: "He is considered the father of theoretical computer science. The machine itself has his name.",
    level: 30,
    roundId: 1,
    maxPoints: 15,
    options: [
      {
        option: "Polonium",
        isCorrect: false,
        code: null,
        questionId: 17,
      },
      {
        option: "Technetium",
        isCorrect: true,
        code: null,
        questionId: 17,
      },
      {
        option: "Francium",
        isCorrect: false,
        code: null,
        questionId: 17,
      },
      {
        option: "Neptunium",
        isCorrect: false,
        code: null,
        questionId: 17,
      },
    ],
  },
];
